{
  "Version":"2012-10-17",
  "Statement":[
    { 
      "Effect":"Allow", 
      "Action":[ 
          "s3:GetReplicationConfiguration",
          "s3:ListBucket" ],
      "Resource":"${source_bucket_arn}" 
    },
    { 
      "Effect":"Allow", 
      "Action":[
        "s3:GetObjectVersion",
        "s3:GetObjectVersionForReplication",
        "s3:GetObjectVersionAcl",
        "s3:GetObjectVersionTagging",
        "s3:GetObjectRetention",
        "s3:GetObjectLegalHold"
      ],
      "Resource":"${source_bucket_arn}/*" 
    },
    { "Effect":"Allow", 
      "Action":[
        "s3:ReplicateObject",
        "s3:ReplicateDelete",
        "s3:ReplicateTags",
        "s3:ObjectOwnerOverrideToBucketOwner"
      ],
      "Resource":[
        "${destination_bucket_arn}",
        "${destination_bucket_arn}/*"
      ]
    }
  ]
}